#define _CRT_SECURE_NO_DEPRECATE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/token.h"
#include "../include/helper.h"

// use fopen etc
// Generated by scanner.flex
extern FILE *yyin;   // Input file for the scanner to use.
extern int yylex();  // Scans text, returns 0 on EOF.
extern int yylineno; // Line number of the last scanned text.
extern char *yytext; // Actual text scanned

extern int EXIT_CODE;
void run_scan(const char *filename);

int main(int argc, char *argv[]) {
    const char *option = argv[1];
    const char *filename = argv[2];

    if (argc < 3) {
        fprintf(stderr, "Usage: %s -scan sourcefile.bminor\n", argv[0]);
        exit(1);
    }

    if (strcmp(option, "-scan") == 0) run_scan(filename); 
    else {
        fprintf(stderr, "Unknown option: %s\n", option);
        exit(1);
    }

    return EXIT_CODE;
}

void print_comment(int* token) {
  // Print the begin symbol
  printf("TOKEN_COMMENT: %s", yytext);
  // goto next after printing
  *token = yylex();
  while(*token != TOKEN_COMMENT_END) {
    // print till the ending comment token
    printf("%s", yytext);
    // next token
    *token = yylex();
  }
  // print end symbol
  printf("%s", yytext);
}

void run_scan(const char *filename) {
    // Open the file for reading
    yyin = fopen(filename, "r");

    // while not EOF
    int token = -1;
    while((token = yylex()) != TOKEN_EOF) {
      if(token == TOKEN_ERROR) {
        EXIT_CODE = 1;
        fprintf(stderr, "token code: %d, %s: %s\n", token, TOKEN_LOOKUP[token], yytext);
      } else {
         fprintf(stdout, "%s: %s\n", TOKEN_LOOKUP[token], yytext);
        }
    }

    fclose(yyin);
    
    if(EXIT_CODE == 1) exit(1);
}
